name: output issue details
on:
    issues:
      types: [opened]
    workflow_dispatch: 
jobs:
    info:
        runs-on: ubuntu-20.04
        steps:
            - name: display metadata
              run: echo ${{ $GITHUB_ENV }}
