name: output issue details
on:
    issues:
      types: [opened]
jobs:
    info:
        runs-on: ubuntu-22.04
        steps:
            - name: display metadata
              run: echo "${{ github }}"